{% set name = "fswatch" %}
{% set version = "1.11.2" %}
{% set sha256 = "b7dadb84848ce666aac0311f9b4c739fbfee6a90c6097807a1f45ad4367294c2" %}

{% set AM_VERSION = os.environ.get("AM_VERSION", "")|string %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/emcrisostomo/fswatch/releases/download/{{ version }}/fswatch-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

  script_env:
    - AM_VERSION

{% if AM_VERSION == "" %}
  skip: true               # [win]
{% elif AM_VERSION != "" %}
  skip: true               # [unix]
{% endif %}


requirements:
  build:
    - posix                        # [win]
    - toolchain
    - m2w64-toolchain              # [win]
    - m2-autoconf                  # [win]
    - m2-automake{{ AM_VERSION }}  # [win]
    - libtool                      # [unix]
    - m2-libtool                   # [win]
    - m2-gettext-devel             # [win]
    - m2-xz                        # [win]

  run:
    - m2w64-gcc-libs               # [win]
    - m2-gettext-devel             # [win]

test:
  commands:
    - fswatch --help
    - test -d "${PREFIX}/include/libfswatch"              # [unix]
    - test -f "${PREFIX}/lib/libfswatch${SHLIB_EXT}"      # [unix]
    - conda inspect linkages -p "${PREFIX}" "{{ name }}"  # [unix]
    - conda inspect objects -p "${PREFIX}" "{{ name }}"   # [osx]

about:
  home: https://github.com/emcrisostomo/fswatch
  license: GPL-3.0
  license_family: GPL
  license_file: COPYING
  summary: |
    "A cross-platform file change monitor with multiple backends: Apple OS X
     File System Events, *BSD kqueue, Solaris/Illumos File Events Notification,
     Linux inotify, Microsoft Windows and a stat()-based backend."

extra:
  recipe-maintainers:
    - jakirkham
