{% set name = "fswatch" %}
{% set version = "1.12.0" %}
{% set sha256 = "8042da283b34dc383ff6321254163e378d4f3cd5d8df87ff608f811ea33e6a83" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/emcrisostomo/fswatch/releases/download/{{ version }}/fswatch-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - libtool                # [unix]
  host:

test:
  commands:
    - fswatch --help
    - test -d "${PREFIX}/include/libfswatch"              # [unix]
    - test -f "${PREFIX}/lib/libfswatch${SHLIB_EXT}"      # [unix]
    - conda inspect linkages -p "${PREFIX}" "{{ name }}"  # [unix]
    - conda inspect objects -p "${PREFIX}" "{{ name }}"   # [osx]

about:
  home: https://github.com/emcrisostomo/fswatch
  license: GPL-3.0
  license_family: GPL
  license_file: COPYING
  summary: |
    "A cross-platform file change monitor with multiple backends: Apple OS X
     File System Events, *BSD kqueue, Solaris/Illumos File Events Notification,
     Linux inotify, Microsoft Windows and a stat()-based backend."

extra:
  recipe-maintainers:
    - jakirkham
