travis:
  secure:
    BINSTAR_TOKEN: hAN08I+egqygYNRJm0PvGTEG4T10ei7PLIe9uNI9p59TfIjVOCb2GSoodZtM1d8fW6Dvd5a3vNF13aZDFh8dtKtvjCq+iJATR5kwfKIDxsteA9Co24mGHD1WJH2KGDXaTbBuVFxikzMBng9B7EJO4vsnKKHxx0vf3W8aQE2rxrXb2/3kdOjKDtm8lW1fiReG5feeFR2zvMGBbWiKjM/zuQFnqx4ORwWFddELBEDR0VDrhU1WgGXjfFpigBYeS+E2AB8hEEv3lMUeSFWGsY+Q60Q797gSDT5CnqJGpDVOdf9VKywN4fugS0v9GF2TwBERjR7ana0d0bWrMIUm/V2+qa/6RICjALDLJTJMvlld5hNRS5V5VmKKAY3mZCWsXeRc4fPSD99zeeP97PXEyd5zGNuqFqduanedImTgR12z+huzzUkkwEc6TD/dOWxjTbukX/HUNtZfcwyNbl8x6lrvzDMLTGPzKEclCV85THndNdgjHCy/a3cisTsW+amqXGNt7dkzxe9tqlJNrZm7sKLgGsH9lK+wTL16tc1RL4YFpvqork5w2Bn1wYv1eYFS+LFBbLO0TdrfqCC3ZQRbuLB5r+Ra0BB/EY3cgLYUozYSv4f75X2TYdbKsg6lYOlFzKZIvDMeO72Dd+7dNm9Uzu80Ue4y+CA3KD35DS6m1+q0xFM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
